HamlPHP: FilterContainer Class Reference
FilterContainer Class Reference
Public Member Functions
__construct ($filters=array())
addFilter (Filter $filter)
getFilters ()
getFilter ($identifier)
Private Attributes
$_filters = array()
Detailed Description
Definition at line 5 of file FilterContainer.php.
Constructor & Destructor Documentation
__construct ($ filters = array())
Definition at line 9 of file FilterContainer.php.
References addFilter().
Member Function Documentation
addFilter (Filter $ filter)
Definition at line 16 of file FilterContainer.php.
References Filter::getIdentifier().
Referenced by __construct().
getFilter ($ identifier)
Definition at line 26 of file FilterContainer.php.
getFilters ()
Definition at line 21 of file FilterContainer.php.
Field Documentation
$_filters = array() [private]
Definition at line 7 of file FilterContainer.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/Filter/FilterContainer.php