HamlPHP: HamlNode Class Reference
HamlNode Class Reference
Public Member Functions
__construct ($line)
getSpaces ()
setIndentationLevel ($level)
getRawHaml ()
getHaml ()
render ()
Private Member Functions
createSpaces ()
Private Attributes
$_rawHaml
$_haml
$_spaces
Detailed Description
Definition at line 3 of file HamlNode.php.
Constructor & Destructor Documentation
__construct ($ line)
Reimplemented in CommentNode, DoctypeNode, and TagNode.
Definition at line 9 of file HamlNode.php.
References RootNode::__construct(), and setIndentationLevel().
Member Function Documentation
createSpaces () [private]
Definition at line 52 of file HamlNode.php.
References RootNode::getIndentationLevel().
Referenced by setIndentationLevel().
getHaml ()
Definition at line 47 of file HamlNode.php.
Referenced by ElementNode::__construct(), CommentNode::identifyCommentType(), FilterNode::render(), CommentNode::render(), PlainFilter::renderChildrenHaml(), and CommentNode::renderHtmlCommentBody().
getRawHaml ()
Definition at line 42 of file HamlNode.php.
Referenced by PlainFilter::renderChildrenHaml().
getSpaces ()
Definition at line 17 of file HamlNode.php.
Referenced by PhpFilter::filter(), JavascriptFilter::filter(), CssFilter::filter(), TagNode::generateTagContent(), TagNode::render(), CommentNode::renderConditionalComment(), ElementNode::renderHtml(), CommentNode::renderHtmlComment(), CommentNode::renderHtmlCommentBody(), and ElementNode::renderTagContent().
render ()
Reimplemented from RootNode.
Reimplemented in CommentNode, DoctypeNode, ElementNode, FilterNode, and TagNode.
Definition at line 63 of file HamlNode.php.
References RootNode::hasChildren(), and RootNode::renderChildren().
setIndentationLevel ($ level)
Reimplemented from RootNode.
Definition at line 22 of file HamlNode.php.
References createSpaces(), RootNode::getChildren(), RootNode::getIndentationLevel(), and RootNode::hasChildren().
Referenced by __construct(), JavascriptFilter::filter(), and CssFilter::filter().
Field Documentation
$_haml [private]
Definition at line 6 of file HamlNode.php.
$_rawHaml [private]
Definition at line 5 of file HamlNode.php.
$_spaces [private]
Definition at line 7 of file HamlNode.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/HamlNode.php