HamlPHP: FilterNode Class Reference
FilterNode Class Reference
Public Member Functions
__construct ($line, FilterContainer $container=null)
render ()
Private Attributes
$_filterContainer = null
Detailed Description
Definition at line 3 of file FilterNode.php.
Constructor & Destructor Documentation
__construct ($ line, FilterContainer $ container = null)
Definition at line 7 of file FilterNode.php.
References RootNode::__construct().
Member Function Documentation
render ()
Reimplemented from HamlNode.
Definition at line 13 of file FilterNode.php.
References HamlNode::getHaml(), and Interpolation::render().
Field Documentation
$_filterContainer = null [private]
Definition at line 5 of file FilterNode.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/FilterNode.php