HamlPHP: ElementNode Class Reference
ElementNode Class Reference
Public Member Functions
__construct ($line, $compiler)
render ()
Private Member Functions
renderHtml (Element $element)
_renderArrayValue ($parts, $separator= ' ', $context= 'txt')
renderTagContent ($content)
Private Attributes
$_phpVariable
$_el
Detailed Description
Definition at line 7 of file ElementNode.php.
Constructor & Destructor Documentation
__construct ($ line, $ compiler)
Definition at line 16 of file ElementNode.php.
References RootNode::__construct(), and HamlNode::getHaml().
Member Function Documentation
_renderArrayValue ($ parts, $ separator = ' ', $ context = 'txt') [private]
Joins the string $parts together using $separator but format the return according to context. This method concatenates all the parts using $separtor as glue. If the context is 'txt' and at least one part is php, the returned string will be encapsuled inside <?php ... ?> If the context is 'php' the string returned will be a valid php code.
   _renderArrayValue(array(
     array('t' => 'str', 'v' => 'a',
     array('t' => 'str', 'v' => 'b'));                  # -> a_b
   _renderArrayValue(array(
     array('t' => 'str', 'v' => 'a',
     array('t' => 'str', 'v' => 'b'), 'php');   # -> 'a_b'
   _renderArrayValue(array(
     array('t' => 'str', 'v' => 'a',
     array('t' => 'php', 'v' => '$b'));                 # -> <?php echo 'a_'.$b; ?>
   _renderArrayValue(array(
     array('t' => 'str', 'v' => 'a',
     array('t' => 'php', 'v' => '$b'), 'php');  # -> 'a_'.$b
Parameters:
$arr_parts The components of the id
$context The context into which the value will be inserted. Can be 'txt' (default) or 'php'
Definition at line 154 of file ElementNode.php.
Referenced by renderHtml().
render ()
Reimplemented from HamlNode.
Definition at line 24 of file ElementNode.php.
References renderHtml().
renderHtml (Element $ element) [private]
Definition at line 29 of file ElementNode.php.
References _renderArrayValue(), Element::getAttributes(), RootNode::getIndentationLevel(), Element::getInlineContent(), HamlNode::getSpaces(), Element::getTag(), renderTagContent(), and Element::useAttsHelper().
Referenced by render().
renderTagContent ($ content) [private]
Definition at line 198 of file ElementNode.php.
References HamlNode::getSpaces(), RootNode::hasChildren(), and RootNode::renderChildren().
Referenced by renderHtml().
Field Documentation
$_el [private]
Definition at line 14 of file ElementNode.php.
$_phpVariable [private]
Definition at line 9 of file ElementNode.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/ElementNode.php