HamlPHP: DoctypeNode Class Reference
DoctypeNode Class Reference
Public Member Functions
__construct ($line)
render ()
Data Fields
const XHTML10_T = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'
const XHTML10_S = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'
const XHTML10_F = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">'
const HTML5 = '<!DOCTYPE html>'
Private Member Functions
renderDoctype ()
Private Attributes
$_type
Detailed Description
Definition at line 5 of file DoctypeNode.php.
Constructor & Destructor Documentation
__construct ($ line)
Reimplemented from HamlNode.
Definition at line 14 of file DoctypeNode.php.
References RootNode::__construct().
Member Function Documentation
render ()
Reimplemented from HamlNode.
Definition at line 21 of file DoctypeNode.php.
References renderDoctype().
renderDoctype () [private]
Definition at line 27 of file DoctypeNode.php.
References HTML5, XHTML10_F, XHTML10_S, and XHTML10_T.
Referenced by render().
Field Documentation
$_type [private]
Definition at line 12 of file DoctypeNode.php.
const HTML5 = '<!DOCTYPE html>'
Definition at line 10 of file DoctypeNode.php.
Referenced by renderDoctype().
const XHTML10_F = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">'
Definition at line 9 of file DoctypeNode.php.
Referenced by renderDoctype().
const XHTML10_S = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">'
Definition at line 8 of file DoctypeNode.php.
Referenced by renderDoctype().
const XHTML10_T = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'
Definition at line 7 of file DoctypeNode.php.
Referenced by renderDoctype().
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/DoctypeNode.php