HamlPHP: RootNode Class Reference
RootNode Class Reference
Public Member Functions
__construct ()
setParent (RootNode $node)
getParent ()
hasParent ()
setIndentationLevel ($level)
getIndentationLevel ()
addNode (RootNode $node=null)
getChildren ()
hasChildren ()
renderChildren ()
render ()
shouldContain ($node)
Protected Member Functions
shouldGoInsideLastNode ($node)
Private Attributes
$_children
$_indentation
$_childrenCount
$_parent
Detailed Description
Definition at line 3 of file RootNode.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 10 of file RootNode.php.
Referenced by TagNode::__construct(), HamlNode::__construct(), FilterNode::__construct(), ElementNode::__construct(), DoctypeNode::__construct(), and CommentNode::__construct().
Member Function Documentation
addNode (RootNode $ node = null)
Definition at line 43 of file RootNode.php.
References shouldGoInsideLastNode().
getChildren ()
Definition at line 74 of file RootNode.php.
Referenced by PlainFilter::filter(), PlainFilter::renderChildrenHaml(), and HamlNode::setIndentationLevel().
getIndentationLevel ()
Definition at line 38 of file RootNode.php.
Referenced by HamlNode::createSpaces(), JavascriptFilter::filter(), CssFilter::filter(), ElementNode::renderHtml(), and HamlNode::setIndentationLevel().
getParent ()
Definition at line 23 of file RootNode.php.
Referenced by PlainFilter::renderChildrenHaml().
hasChildren ()
Definition at line 79 of file RootNode.php.
Referenced by HamlNode::render(), PlainFilter::renderChildrenHaml(), CommentNode::renderHtmlCommentBody(), ElementNode::renderTagContent(), and HamlNode::setIndentationLevel().
hasParent ()
Definition at line 28 of file RootNode.php.
render ()
Reimplemented in CommentNode, DoctypeNode, ElementNode, FilterNode, HamlNode, and TagNode.
Definition at line 95 of file RootNode.php.
References renderChildren().
renderChildren ()
Definition at line 84 of file RootNode.php.
Referenced by TagNode::generateTagContent(), render(), HamlNode::render(), CommentNode::renderHtmlCommentBody(), and ElementNode::renderTagContent().
setIndentationLevel ($ level)
Reimplemented in HamlNode.
Definition at line 33 of file RootNode.php.
setParent (RootNode $ node)
Definition at line 18 of file RootNode.php.
shouldContain ($ node)
Definition at line 100 of file RootNode.php.
shouldGoInsideLastNode ($ node) [protected]
Definition at line 62 of file RootNode.php.
Referenced by addNode().
Field Documentation
$_children [private]
Definition at line 5 of file RootNode.php.
$_childrenCount [private]
Definition at line 7 of file RootNode.php.
$_indentation [private]
Definition at line 6 of file RootNode.php.
$_parent [private]
Definition at line 8 of file RootNode.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/RootNode.php