HamlPHP: TagNode Class Reference
TagNode Class Reference
Public Member Functions
__construct ($line)
render ()
Data Fields
const CODE_PATTERN = '/(?P<mode>[-=])\s*(?P<code>(?P<tag>\w+)\s*([^\:]+)(?P<colon>:)?\s*$|[^\r\n]+)/'
const SILENT_MODE = '-'
const LOUD_MODE = '='
Private Member Functions
generateTagContent ()
Private Attributes
$_tags
$_line = null
$_isTag = false
$_mode
$_tag
$_code
Detailed Description
Definition at line 11 of file TagNode.php.
Constructor & Destructor Documentation
__construct ($ line)
Reimplemented from HamlNode.
Definition at line 46 of file TagNode.php.
References RootNode::__construct(), CODE_PATTERN, and LOUD_MODE.
Member Function Documentation
generateTagContent () [private]
Definition at line 82 of file TagNode.php.
References HamlNode::getSpaces(), and RootNode::renderChildren().
Referenced by render().
render ()
Reimplemented from HamlNode.
Definition at line 70 of file TagNode.php.
References generateTagContent(), HamlNode::getSpaces(), and LOUD_MODE.
Field Documentation
$_code [private]
Definition at line 40 of file TagNode.php.
$_isTag = false [private]
Definition at line 22 of file TagNode.php.
$_line = null [private]
Definition at line 20 of file TagNode.php.
$_mode [private]
Definition at line 28 of file TagNode.php.
$_tag [private]
Definition at line 34 of file TagNode.php.
$_tags [private]
Initial value:
 array(
    'for' => 'endfor',
    'if' => 'endif',
    'while' => 'endwhile',
    'foreach' => 'endforeach',
  )
Definition at line 13 of file TagNode.php.
const CODE_PATTERN = '/(?P<mode>[-=])\s*(?P<code>(?P<tag>\w+)\s*([^\:]+)(?P<colon>:)?\s*$|[^\r\n]+)/'
Definition at line 42 of file TagNode.php.
Referenced by __construct().
const LOUD_MODE = '='
Definition at line 44 of file TagNode.php.
Referenced by __construct(), and render().
const SILENT_MODE = '-'
Definition at line 43 of file TagNode.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/TagNode.php