HamlPHP: Compiler Class Reference
Compiler Class Reference
Public Member Functions
__construct (NodeFactory $factory=null)
getFilterContainer ()
parseFile ($fileName)
parseString ($rawString)
parseLines (array $rawLines=array())
Protected Member Functions
initializeNodeFactory ()
Private Attributes
$_nodeFactory = null
Detailed Description
Definition at line 10 of file Compiler.php.
Constructor & Destructor Documentation
__construct (NodeFactory $ factory = null)
Definition at line 14 of file Compiler.php.
References initializeNodeFactory().
Member Function Documentation
getFilterContainer ()
Definition at line 20 of file Compiler.php.
Referenced by initializeNodeFactory().
initializeNodeFactory () [protected]
Definition at line 29 of file Compiler.php.
References getFilterContainer().
Referenced by __construct().
parseFile ($ fileName)
Compiles haml from a file.
Parameters:
string $fileName
Definition at line 39 of file Compiler.php.
References parseString().
parseLines (array $ rawLines = array())
Compiles haml from an array of lines.
Parameters:
array $rawLines
Definition at line 60 of file Compiler.php.
Referenced by parseString().
parseString ($ rawString)
Compiles haml from a string.
Parameters:
string $rawString
Definition at line 49 of file Compiler.php.
References parseLines().
Referenced by parseFile().
Field Documentation
$_nodeFactory = null [private]
Definition at line 12 of file Compiler.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/Compiler.php