HamlPHP: BaseException Class Reference
BaseException Class Reference
Public Member Functions
__construct ($message, $tokens=array())
getGuiltyFile ()
getGuiltyLine ()
getClass ()
getFunction ()
getGuiltyClass ()
getGuiltyFunction ()
getOrigMsg ()
setClass ($class)
setFunction ($function)
setGuiltyClass ($guiltyClass)
setGuiltyFunction ($guiltyFunction)
setOrigMsg ($origMsg)
setGuiltyFile ($filePath)
setGuiltyLine ($lineNumber)
getSourceLines ()
setSourceLines ($source)
setCode ($code)
Protected Member Functions
grabTraceData ()
updateMessage ()
Static Protected Member Functions
static replacePlaceholder (array $match)
Protected Attributes
$message = 'Unknown exception'
$origMsg = 'Unknown exception'
$code = 0
$file
$line
$function
$class
$guiltyFile
$guiltyLine
$guiltyFunction
$guiltyClass
Private Attributes
$source
Detailed Description
Class BaseException
This is the base exception class for all classes in the framework. This class provides core funcionality, like automatically replacing available placeholders.
The placeholders provided by this class are:
{{code}} - The user defined exception code {{file}} - The file where the exception was thrown {{guiltyFile}} - The file guilty for the exception {{line}} - The line where the exception was thrown {{guiltyLine}} - The line guilty for the exception {{function}} - The function or method where the exception was thrown {{guiltyFunction}} - The function or method where the exception was thrown {{class}} - The class, in case the exception occurs inside a method, wich the method belongs to {{guiltyClass}} - The class, in case the exception occurs inside a method, wich the method belongs to
Author:
Saulo Vallory <email@saulovallory.com>
Definition at line 24 of file BaseException.php.
Constructor & Destructor Documentation
__construct ($ message, $ tokens = array())
Constructor
Parameters:
string $message The error message. This can be a string or an instance of ErrorMsg. The other parameters will be used to replace placeholders ({0:param name}, {1:param}, {2:name}, etc.) in the message.
Reimplemented in UndefinedPropertyException, and ReadOnlyPropertyException.
Definition at line 119 of file BaseException.php.
References $message, and updateMessage().
Member Function Documentation
getClass ()
Returns:
string
Definition at line 184 of file BaseException.php.
References grabTraceData().
getFunction ()
Returns:
string
Definition at line 197 of file BaseException.php.
References grabTraceData().
getGuiltyClass ()
Returns:
string
Definition at line 210 of file BaseException.php.
getGuiltyFile ()
Get the file guilty for the exception
Returns:
string
Definition at line 167 of file BaseException.php.
getGuiltyFunction ()
Returns:
string
Definition at line 217 of file BaseException.php.
getGuiltyLine ()
Get the line guilty for the exception
Returns:
int
Definition at line 177 of file BaseException.php.
getOrigMsg ()
Returns:
string
Definition at line 224 of file BaseException.php.
getSourceLines ()
Definition at line 326 of file BaseException.php.
grabTraceData () [protected]
This function grabs all the possible useful data from trace and put it on class properties
Definition at line 232 of file BaseException.php.
Referenced by getClass(), and getFunction().
static replacePlaceholder (array $ match) [static, protected]
This function gets an array with two items the first is the placeholder found and the second is the placeholder name (ex: {{file}} and file). The purpose of this function is replace message placeholders with its values. If you want to extend this functionality you can override this function, but you must call this function at the end of yours.
Parameters:
array $match
Definition at line 145 of file BaseException.php.
setClass ($ class)
Parameters:
string $class
Definition at line 254 of file BaseException.php.
References $class, and updateMessage().
setCode ($ code)
Definition at line 336 of file BaseException.php.
References $code.
setFunction ($ function)
Parameters:
string $function
Definition at line 265 of file BaseException.php.
References $function.
setGuiltyClass ($ guiltyClass)
Parameters:
string $guiltyClass
Definition at line 272 of file BaseException.php.
References $guiltyClass.
setGuiltyFile ($ filePath)
Set the line file for the exception
Parameters:
string $filePath
Definition at line 297 of file BaseException.php.
setGuiltyFunction ($ guiltyFunction)
Parameters:
string $guiltyFunction
Definition at line 280 of file BaseException.php.
References $guiltyFunction.
setGuiltyLine ($ lineNumber)
Set the line guilty for the exception
Parameters:
int $lineNumber
Definition at line 308 of file BaseException.php.
setOrigMsg ($ origMsg)
Parameters:
string $origMsg
Definition at line 288 of file BaseException.php.
References $origMsg.
setSourceLines ($ source)
Definition at line 331 of file BaseException.php.
References $source.
updateMessage () [protected]
This function updates the exception message based on the original message and the current object property values
Definition at line 319 of file BaseException.php.
Referenced by __construct(), and setClass().
Field Documentation
$class [protected]
Definition at line 75 of file BaseException.php.
Referenced by setClass().
$code = 0 [protected]
Definition at line 47 of file BaseException.php.
Referenced by setCode().
$file [protected]
Definition at line 54 of file BaseException.php.
$function [protected]
Definition at line 68 of file BaseException.php.
Referenced by setFunction().
$guiltyClass [protected]
Definition at line 103 of file BaseException.php.
Referenced by setGuiltyClass().
$guiltyFile [protected]
Definition at line 82 of file BaseException.php.
$guiltyFunction [protected]
Definition at line 96 of file BaseException.php.
Referenced by setGuiltyFunction().
$guiltyLine [protected]
Definition at line 89 of file BaseException.php.
$line [protected]
Definition at line 61 of file BaseException.php.
$message = 'Unknown exception' [protected]
Definition at line 32 of file BaseException.php.
Referenced by __construct().
$origMsg = 'Unknown exception' [protected]
Definition at line 40 of file BaseException.php.
Referenced by setOrigMsg().
$source [private]
Definition at line 110 of file BaseException.php.
Referenced by setSourceLines().
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/Util/BaseException.php