HamlPHP: CommentNode Class Reference
CommentNode Class Reference
Public Member Functions
__construct ($line)
render ()
Data Fields
const HTML_COMMENT = '/'
const HAML_COMMENT = '-#'
const CONDITIONAL_COMMENT = "/\/\[([^\\]]+)\]/"
const HTML_COMMENT_TYPE = 1
const HAML_COMMENT_TYPE = 2
const CONDITIONAL_COMMENT_TYPE = 3
Private Member Functions
identifyCommentType ()
renderHtmlComment ()
renderHtmlCommentBody ()
renderConditionalComment ()
renderHamlComment ()
Private Attributes
$_commentType = null
$_conditionalMatches = array()
Detailed Description
Definition at line 3 of file CommentNode.php.
Constructor & Destructor Documentation
__construct ($ line)
Reimplemented from HamlNode.
Definition at line 15 of file CommentNode.php.
References RootNode::__construct(), and identifyCommentType().
Member Function Documentation
identifyCommentType () [private]
Definition at line 21 of file CommentNode.php.
References CONDITIONAL_COMMENT, CONDITIONAL_COMMENT_TYPE, HamlNode::getHaml(), HAML_COMMENT, HAML_COMMENT_TYPE, HTML_COMMENT, and HTML_COMMENT_TYPE.
Referenced by __construct().
render ()
Reimplemented from HamlNode.
Definition at line 37 of file CommentNode.php.
References CONDITIONAL_COMMENT_TYPE, HamlNode::getHaml(), HAML_COMMENT_TYPE, HTML_COMMENT_TYPE, renderConditionalComment(), renderHamlComment(), and renderHtmlComment().
renderConditionalComment () [private]
Definition at line 77 of file CommentNode.php.
References HamlNode::getSpaces(), and renderHtmlCommentBody().
Referenced by render().
renderHamlComment () [private]
Definition at line 88 of file CommentNode.php.
Referenced by render().
renderHtmlComment () [private]
Definition at line 59 of file CommentNode.php.
References HamlNode::getSpaces(), and renderHtmlCommentBody().
Referenced by render().
renderHtmlCommentBody () [private]
Definition at line 68 of file CommentNode.php.
References HamlNode::getHaml(), HamlNode::getSpaces(), RootNode::hasChildren(), and RootNode::renderChildren().
Referenced by renderConditionalComment(), and renderHtmlComment().
Field Documentation
$_commentType = null [private]
Definition at line 12 of file CommentNode.php.
$_conditionalMatches = array() [private]
Definition at line 13 of file CommentNode.php.
const CONDITIONAL_COMMENT = "/\/\[([^\\]]+)\]/"
Definition at line 7 of file CommentNode.php.
Referenced by identifyCommentType().
const CONDITIONAL_COMMENT_TYPE = 3
Definition at line 10 of file CommentNode.php.
Referenced by identifyCommentType(), and render().
const HAML_COMMENT = '-#'
Definition at line 6 of file CommentNode.php.
Referenced by identifyCommentType().
const HAML_COMMENT_TYPE = 2
Definition at line 9 of file CommentNode.php.
Referenced by identifyCommentType(), and render().
const HTML_COMMENT = '/'
Definition at line 5 of file CommentNode.php.
Referenced by identifyCommentType().
const HTML_COMMENT_TYPE = 1
Definition at line 8 of file CommentNode.php.
Referenced by identifyCommentType(), and render().
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/CommentNode.php