HamlPHP: HamlPHP Class Reference
HamlPHP Class Reference
Public Member Functions
__construct (Storage $storage, Config $config=null)
getConfiguration ()
setContentEvaluator (ContentEvaluator $contentEvaluator)
setCompiler (Compiler $compiler)
getCompiler ()
parseFile ($fileName, array $templateVars=array())
getContentFromStorage ($fileName)
Private Member Functions
generateFileId ($filename)
Private Attributes
$_compiler = null
$_config = null
$_storage = null
$_contentEvaluator = null
Detailed Description
Definition at line 7 of file HamlPHP.php.
Constructor & Destructor Documentation
__construct (Storage $ storage, Config $ config = null)
Definition at line 14 of file HamlPHP.php.
References setContentEvaluator().
Member Function Documentation
generateFileId ($ filename) [private]
Definition at line 82 of file HamlPHP.php.
Referenced by getContentFromStorage(), and parseFile().
getCompiler ()
Definition at line 42 of file HamlPHP.php.
getConfiguration ()
Definition at line 27 of file HamlPHP.php.
getContentFromStorage ($ fileName)
Returns content from a storage
Parameters:
string $fileName
Returns:
string
Definition at line 64 of file HamlPHP.php.
References generateFileId().
Referenced by parseFile().
parseFile ($ fileName, array $ templateVars = array())
Parses a haml file and returns a cached path to the file.
Parameters:
string $fileName
Definition at line 52 of file HamlPHP.php.
References generateFileId(), and getContentFromStorage().
setCompiler (Compiler $ compiler)
Definition at line 37 of file HamlPHP.php.
setContentEvaluator (ContentEvaluator $ contentEvaluator)
Definition at line 32 of file HamlPHP.php.
Referenced by __construct().
Field Documentation
$_compiler = null [private]
Definition at line 9 of file HamlPHP.php.
$_config = null [private]
Definition at line 10 of file HamlPHP.php.
$_contentEvaluator = null [private]
Definition at line 12 of file HamlPHP.php.
$_storage = null [private]
Definition at line 11 of file HamlPHP.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/HamlPHP.php