HamlPHP: Element Class Reference
Element Class Reference
Public Member Functions
__construct ($line, Compiler $compiler)
getTag ()
getId ()
isPhpVariable ()
getClasses ()
getAttributes ()
getInlineContent ()
useAttsHelper ()
Data Fields
const ELEMENT = '%'
const ID = '#'
const KLASS = '.'
Private Member Functions
parseHaml ()
_containsPhpAttribute (array $att_arr)
_mergeAttributes ($att_arrays)
_parseObjRef ($scanner)
_parseClassAndId ($list)
_parseHtmlAttrs (StringScanner $scanner)
_parseHashAttrs (StringScanner $scanner)
balance ($scanner_or_line, $start_char, $finish_char, $count=0)
_interpolate ($str)
Private Attributes
$_haml = null
$_tag = null
$_id = null
$_classes = null
$_inlineContent = null
$_php = false
$_attributes = null
$_scanner
$_nukeOuterWhitespace
$_nukeInnerWhitespace
$_selfClosing = false
$_preserveWhitespace = false
$_useAttsHelper
$_compiler
Detailed Description
Definition at line 9 of file Element.php.
Constructor & Destructor Documentation
__construct ($ line, Compiler $ compiler)
Definition at line 38 of file Element.php.
References parseHaml().
Member Function Documentation
_containsPhpAttribute (array $ att_arr) [private]
Definition at line 180 of file Element.php.
Referenced by parseHaml().
_interpolate ($ str) [private]
Definition at line 539 of file Element.php.
Referenced by _parseHashAttrs(), and parseHaml().
_mergeAttributes ($ att_arrays) [private]
Definition at line 191 of file Element.php.
Referenced by parseHaml().
_parseClassAndId ($ list) [private]
Definition at line 256 of file Element.php.
Referenced by parseHaml().
_parseHashAttrs (StringScanner $ scanner) [private]
Parameters:
StringScanner $scanner
Returns:
array an array with the parsed elements
Definition at line 370 of file Element.php.
References _interpolate(), balance(), StringScanner::concat(), StringScanner::scan(), and StringScanner::scanUntil().
Referenced by parseHaml().
_parseHtmlAttrs (StringScanner $ scanner) [private]
Definition at line 280 of file Element.php.
References StringScanner::concat(), and StringScanner::scan().
Referenced by parseHaml().
_parseObjRef ($ scanner) [private]
Definition at line 232 of file Element.php.
Referenced by parseHaml().
balance ($ scanner_or_line, $ start_char, $ finish_char, $ count = 0) [private]
Checks if the string has a balanced amount of $start_char and $finish_char pairs If you pass a scanner, the pointer of the scanner will be altered!
Parameters:
$scanner_or_line The line or a scanner to balance
$start_char The balancing start char
$finish_char The balancing end char
$count [Optional] The current balance count
Returns:
array [$balanced, $balanced_str, $rest, $count]
Definition at line 510 of file Element.php.
Referenced by _parseHashAttrs().
getAttributes ()
Definition at line 603 of file Element.php.
Referenced by ElementNode::renderHtml().
getClasses ()
Definition at line 596 of file Element.php.
getId ()
Definition at line 583 of file Element.php.
getInlineContent ()
Definition at line 608 of file Element.php.
Referenced by ElementNode::renderHtml().
getTag ()
Definition at line 578 of file Element.php.
Referenced by ElementNode::renderHtml().
isPhpVariable ()
Definition at line 591 of file Element.php.
parseHaml () [private]
Definition at line 47 of file Element.php.
References HamlPHP::$Config, _containsPhpAttribute(), _interpolate(), _mergeAttributes(), _parseClassAndId(), _parseHashAttrs(), _parseHtmlAttrs(), and _parseObjRef().
Referenced by __construct().
useAttsHelper ()
Definition at line 613 of file Element.php.
Referenced by ElementNode::renderHtml().
Field Documentation
$_attributes = null [private]
Definition at line 24 of file Element.php.
$_classes = null [private]
Definition at line 21 of file Element.php.
$_compiler [private]
Definition at line 36 of file Element.php.
$_haml = null [private]
Definition at line 18 of file Element.php.
$_id = null [private]
Definition at line 20 of file Element.php.
$_inlineContent = null [private]
Definition at line 22 of file Element.php.
$_nukeInnerWhitespace [private]
Definition at line 27 of file Element.php.
$_nukeOuterWhitespace [private]
Definition at line 26 of file Element.php.
$_php = false [private]
Definition at line 23 of file Element.php.
$_preserveWhitespace = false [private]
Definition at line 30 of file Element.php.
$_scanner [private]
Definition at line 25 of file Element.php.
$_selfClosing = false [private]
Definition at line 29 of file Element.php.
$_tag = null [private]
Definition at line 19 of file Element.php.
$_useAttsHelper [private]
Definition at line 31 of file Element.php.
const ELEMENT = '%'
Definition at line 14 of file Element.php.
const ID = '#'
Definition at line 15 of file Element.php.
const KLASS = '.'
Definition at line 16 of file Element.php.
The documentation for this class was generated from the following file:
/projects/wp-haml/hamlphp/src/HamlPHP/Element.php